apiVersion: apps/v1
kind: Deployment
metadata:
  name: okterolvy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okterolvy
  template:
    metadata:
      labels:
        app: okterolvy
    spec:
      containers:
      - image: okteto.dev/okterolvy:latest
        name: okterolvy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f6f903ca-a55a-4848-8ff5-917723fbb0dc"
        - name: Vless_Path
          value: "/vlgsdgyss5"
        - name: Vmess_UUID
          value: "f6f903ca-a55a-4848-8ff5-917723fbb0dc"
        - name: Vmess_Path
          value: "/vmgsetshs6"
        - name: Share_Path
          value: "/v2link"
